### ISSUE TITLE
Corona Virus API link is broken

### ISSUE THREAD

**Issue by mpendulo-dev** [giftmbanda/globalcovid19tracker#1]
The API link has been changed to https://disease.sh/v3/covid-19/countries and that caused the application to break.
![image](https://user-images.githubusercontent.com/79789895/137721497-e45011af-6b8e-4835-a7ee-3065d493e442.png)

**Comment by giftmbanda** [comment]
Thanks, buddy. I have fixed it according to the info you gave, much appreciated 🤝
